development:
  adapter: mysql
  database: twhistory_development
  username: root
  password:
  host: localhost
  encoding: utf8

test: &test 
  adapter: mysql
  database: twhistory_test
  username: root
  password:
  host: localhost
  encoding: utf8

production:
  adapter: mysql
  database: twhistory_production
  username: twhistory
  password: 
  host:  
  port: 10241
  encoding: utf8
    
cucumber: 
  <<: *test