development:
  adapter: mysql
  database: twhistory_development
  username: root
  password:
  host: localhost
  encoding: utf8

test: &test 
  adapter: mysql
  database: twhistory_test
  username: root
  password:
  host: localhost
  encoding: utf8

production:
  adapter: mysql
  database: twhistory_production
  username: twhistory
  password: DR760y5sjedEZdyjlq0A
  host: 3e5b69be.dotcloud.com
  port: 13041
  encoding: utf8
      
cucumber: 
  <<: *test