development:
  adapter: mysql
  database: twhistory_development
  username: root
  password:
  host: localhost
  encoding: utf8

test:
  adapter: mysql
  database: twhistory_test
  username: root
  password:
  host: localhost
  encoding: utf8

staging:
  adapter: mysql
  database: twhistory_staging
  username: twhistory
  password: 
  host: localhost
  encoding: utf8
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql
  database: twhistory_production
  username: twhistory
  password: 
  host: localhost
  encoding: utf8
  socket: /var/lib/mysql/mysql.sock
