development:
  adapter: mysql
  database: twhistory_development
  username: root
  password:
  host: localhost
  encoding: utf8

test:
  adapter: mysql
  database: twhistory_test
  username: root
  password:
  host: localhost
  encoding: utf8
